GBASockServer: remove m_device_number (fixes warning)
It's only used when _DEBUG is defined, so the compiler complains.

Fixes warning:

```
./Source/Core/Core/HW/SI/SI_DeviceGBA.h:44:7: error: private field 'm_device_number' is not used [-Werror,-Wunused-private-field]
  int m_device_number;
      ^
```